# Based on
# - https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: unittest-windows.yaml

on: [push]

env:
  LD_LIBRARY_PATH: 'C:\Program Files\Senzing\g2\lib'
  PYTHONPATH: 'D:\a\g2-sdk-python-next\g2-sdk-python-next\src'
  SENZING_TOOLS_DATABASE_URL: 'sqlite3://na:na@nowhere/C:\Temp\sqlite\G2C.db'

jobs:
  unittest-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        # python-version: ["3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.8"]
        senzingapi-version: [staging]
    name: "unittest Senzing: ${{ matrix.senzingapi-version }}; OS: ${{ matrix.os }}; Python ${{ matrix.python-version }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Senzing API
        uses: Senzing/github-action-install-senzing-api@latest
        with:
          senzingapi-version: ${{ matrix.senzingapi-version }}
      - name: Add to "Path" environment variable
        run: |
          echo "C:\Program Files\Senzing\g2\lib" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Copy /etc files
        run: copy testdata/senzing-license/g2.lic "C:\Program Files\Senzing\g2\etc\g2.lic"
      - name: Copy test database files
        run: mkdir "C:\Temp\sqlite" && copy testdata/sqlite/G2C.db "C:\Temp\sqlite\G2C.db"
      - name: debug - pwd
        run: pwd
      - name: debug - ls
        run: dir
      - name: debug - opt/senzing/g2/lib
        run: dir "C:\Program Files\Senzing\g2\lib"
      - name: Run python unittest
        run: |
          echo "C:\Program Files\Senzing\g2\lib" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo %PATH%
          python3 -m unittest tests/g2config_test.py tests/g2configmgr_test.py tests/g2diagnostic_test.py tests/g2engine_test.py tests/g2engineflags_test.py tests/g2exception_test.py tests/g2hasher_test.py tests/g2product_test.py
